{% set version = "0.99.12" %}
{% set name = "SingleR" %}
{% set bioc = "3.10" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 3c68e3c7c8060ebbd5dbd931607bc8a0
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
# Suggests: testthat, knitr, rmarkdown, BiocStyle, beachmat, SingleCellExperiment, scater, scRNAseq, scran, Matrix, BiocGenerics, ggplot2, pheatmap, grDevices
# SystemRequirements: C++11
requirements:
  host:
    - 'bioconductor-beachmat >=2.1.0,<2.2.0'
    - 'bioconductor-biocneighbors >=1.3.0,<1.4.0'
    - 'bioconductor-biocparallel >=1.19.0,<1.20.0'
    - 'bioconductor-delayedarray >=0.11.0,<0.12.0'
    - 'bioconductor-delayedmatrixstats >=1.7.0,<1.8.0'
    - 'bioconductor-experimenthub >=1.11.0,<1.12.0'
    - 'bioconductor-s4vectors >=0.23.0,<0.24.0'
    - 'bioconductor-summarizedexperiment >=1.15.0,<1.16.0'
    - r-base
    - r-rcpp
  run:
    - 'bioconductor-beachmat >=2.1.0,<2.2.0'
    - 'bioconductor-biocneighbors >=1.3.0,<1.4.0'
    - 'bioconductor-biocparallel >=1.19.0,<1.20.0'
    - 'bioconductor-delayedarray >=0.11.0,<0.12.0'
    - 'bioconductor-delayedmatrixstats >=1.7.0,<1.8.0'
    - 'bioconductor-experimenthub >=1.11.0,<1.12.0'
    - 'bioconductor-s4vectors >=0.23.0,<0.24.0'
    - 'bioconductor-summarizedexperiment >=1.15.0,<1.16.0'
    - r-base
    - r-rcpp
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL-3 + file LICENSE'
  summary: 'Performs unbiased cell type recognition from single-cell RNA sequencing data, by leveraging reference transcriptomic datasets of pure cell types to infer the cell of origin of each single cell independently.'

