{% set version = "2.6" %}

package:
  name: flye
  version: {{ version }}

source:
  #url: https://github.com/fenderglass/Flye/archive/{{ version }}.tar.gz
  url: https://github.com/fenderglass/Flye/archive/flye-devel.tar.gz
  sha256: 7de4f0e4e2d076b43dd7167dcbfaff3eee832b6b88194f304bdf394ae89173af

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - zlib
  host:
    - python
    - zlib
  run:
    - python

test:
  source_files:
    - test/test_toy.py
    - test/ecoli_500kb_reads.fastq.gz
  commands:
    - flye -h | grep Assembly
    - ls -l test
    - python test/test_toy.py


about:
  home: https://github.com/fenderglass/Flye/
  license: BSD-3-Clause
  summary: Fast and accurate de novo assembler for single molecule sequencing reads
